version: '3.8'
services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: studio-in-a-box-clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_DB=studio_in_a_box
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./data/seed:/docker-entrypoint-initdb.d
volumes:
  clickhouse_data:
