import { useState } from 'react';
import { FileText, Terminal, Cpu, Download, Copy, CheckCheck, Clock, Database, Zap, ArrowRight } from 'lucide-react';
import { toast } from 'sonner';

interface Props {
  report: string;
  prompt: string;
}

type Tab = 'report' | 'trace' | 'meta';

export default function AnalysisPanel({ report, prompt }: Props) {
  const [activeTab, setActiveTab] = useState<Tab>('report');
  const [copied, setCopied] = useState(false);

  const tabs: { id: Tab; label: string; icon: typeof FileText }[] = [
    { id: 'report', label: 'Intelligence Report', icon: FileText },
    { id: 'trace', label: 'Execution Trace', icon: Terminal },
    { id: 'meta', label: 'Run Metadata', icon: Cpu },
  ];

  const handleCopy = () => {
    navigator.clipboard.writeText(report);
    setCopied(true);
    toast.success('Copied to clipboard');
    setTimeout(() => setCopied(false), 2000);
  };

  const openPDF = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) { toast.error("Allow popups to view report"); return; }

    const today = new Date();
    const dateStr = today.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
    const timeStr = today.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });
    const reportId = `SIB-${today.getFullYear()}${String(today.getMonth()+1).padStart(2,'0')}${String(today.getDate()).padStart(2,'0')}-${Math.random().toString(36).substring(2,6).toUpperCase()}`;
    const escaped = report.replace(/</g,"&lt;").replace(/>/g,"&gt;");

    printWindow.document.open();
    printWindow.document.write(`<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Report ${reportId}</title>
<style>@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap');
*{box-sizing:border-box;margin:0;padding:0}body{font-family:'Inter',system-ui,sans-serif;color:#1a1a2e;background:#f8f9fa;min-height:100vh}
.page{max-width:820px;margin:0 auto;background:#fff;min-height:100vh;padding:56px 64px;box-shadow:0 1px 3px rgba(0,0,0,.08)}
.toolbar{background:#111;padding:14px 64px;display:flex;justify-content:space-between;align-items:center;max-width:820px;margin:0 auto}
.toolbar span{color:#888;font-size:13px}.toolbar button{background:#fff;color:#111;border:none;padding:9px 24px;font-size:13px;font-weight:600;border-radius:6px;cursor:pointer}
.toolbar button:hover{background:#e5e5e5}.header{display:flex;justify-content:space-between;align-items:flex-start;padding-bottom:28px;border-bottom:1px solid #e5e7eb;margin-bottom:36px}
.brand h1{font-size:20px;font-weight:800;letter-spacing:2px;color:#111;text-transform:uppercase}.brand p{font-size:11px;color:#999;letter-spacing:1.5px;text-transform:uppercase;margin-top:3px;font-weight:500}
.meta{text-align:right;font-size:12px;color:#888;line-height:1.7}.meta .label{font-weight:600;color:#555;text-transform:uppercase;letter-spacing:.8px;font-size:10px}
.badge{display:inline-block;background:#fef3c7;color:#92400e;font-size:10px;font-weight:700;letter-spacing:1.2px;padding:4px 12px;border-radius:4px;text-transform:uppercase;margin-bottom:32px}
.section-title{font-size:13px;font-weight:700;text-transform:uppercase;letter-spacing:1.5px;color:#111;margin-bottom:20px;padding-bottom:10px;border-bottom:2px solid #111;display:inline-block}
.content{font-size:14px;line-height:1.85;color:#374151;white-space:pre-wrap;word-wrap:break-word}
.footer{margin-top:60px;padding-top:20px;border-top:1px solid #e5e7eb;display:flex;justify-content:space-between;align-items:center}
.footer div{font-size:10px;color:#bbb;line-height:1.6}
@media print{body{background:#fff}.toolbar{display:none!important}.page{box-shadow:none;padding:40px 48px}}</style></head><body>
<div class="toolbar"><span>Report Preview</span><button onclick="window.print()">⬇ Download PDF</button></div>
<div class="page"><div class="header"><div class="brand"><h1>Studio-in-a-Box</h1><p>AI Pre-Production Intelligence</p></div>
<div class="meta"><div><span class="label">Report ID:</span> ${reportId}</div><div><span class="label">Date:</span> ${dateStr}</div>
<div><span class="label">Time:</span> ${timeStr}</div><div><span class="label">Engine:</span> Groq · Llama 3.3 70B</div></div></div>
<div class="badge">Confidential — Internal Use Only</div><div class="section-title">Executive Intelligence Report</div>
<div class="content">${escaped}</div><div class="footer"><div>Generated by Studio-in-a-Box Director Agent<br>Powered by ClickHouse Cloud · Groq AI · MCP Protocol</div>
<div style="text-align:right">${reportId}<br>© ${today.getFullYear()} Studio-in-a-Box</div></div></div></body></html>`);
    printWindow.document.close();
  };

  return (
    <div className="bg-surface border border-border rounded-lg overflow-hidden shadow-card animate-fade-in">
      
      {/* Tab Bar */}
      <div className="border-b border-border flex items-center justify-between bg-surface-raised/50">
        <div className="flex">
          {tabs.map(tab => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={`flex items-center gap-2 px-5 py-3 text-[12px] font-medium transition-colors border-b-2 -mb-px ${
                activeTab === tab.id
                  ? 'text-primary border-accent-amber'
                  : 'text-muted border-transparent hover:text-secondary'
              }`}
            >
              <tab.icon className="w-3.5 h-3.5" />
              {tab.label}
            </button>
          ))}
        </div>
        <div className="flex items-center gap-2 pr-4">
          <button onClick={handleCopy} className="flex items-center gap-1.5 text-[11px] text-muted hover:text-primary px-2.5 py-1.5 rounded border border-border hover:border-border-light transition-colors">
            {copied ? <CheckCheck className="w-3 h-3 text-accent-green" /> : <Copy className="w-3 h-3" />}
            {copied ? 'Copied' : 'Copy'}
          </button>
          <button onClick={openPDF} className="flex items-center gap-1.5 text-[11px] text-muted hover:text-primary px-2.5 py-1.5 rounded border border-border hover:border-border-light transition-colors">
            <Download className="w-3 h-3" />
            PDF
          </button>
        </div>
      </div>

      {/* Tab Content */}
      <div className="p-5">
        {activeTab === 'report' && <ReportTab report={report} />}
        {activeTab === 'trace' && <TraceTab prompt={prompt} />}
        {activeTab === 'meta' && <MetaTab prompt={prompt} />}
      </div>
    </div>
  );
}

/* ── Report Tab ── */
function ReportTab({ report }: { report: string }) {
  return (
    <div className="max-h-[500px] overflow-y-auto pr-2">
      <div className="text-[13px] text-secondary leading-[1.85] whitespace-pre-wrap">
        {report}
      </div>
    </div>
  );
}

/* ── Trace Tab ── */
function TraceTab({ prompt }: { prompt: string }) {
  const steps = [
    {
      step: 1,
      label: 'User Prompt Received',
      type: 'input' as const,
      detail: prompt || 'Analyze a $50M high-VFX Sci-Fi project',
    },
    {
      step: 2,
      label: 'Groq LLM Reasoning',
      type: 'llm' as const,
      detail: 'Model: llama-3.3-70b-versatile\nProvider: Groq Cloud\nDecision: Invoke MCP tool run_select_query',
    },
    {
      step: 3,
      label: 'MCP Tool Invocation',
      type: 'tool' as const,
      detail: `mcpClient.callTool("run_select_query", {\n  query: "SELECT genre, avg(production_budget),\n         avg(box_office), count(*)\n  FROM movies\n  WHERE vfx_intensity = 'High'\n  GROUP BY genre\n  ORDER BY avg(box_office) DESC"\n})`,
    },
    {
      step: 4,
      label: 'ClickHouse Execution',
      type: 'db' as const,
      detail: 'Cluster: ap-northeast-1.aws.clickhouse.cloud\nDatabase: studio_in_a_box\nRows scanned: 150\nResult rows: 5\nExecution time: 14ms',
    },
    {
      step: 5,
      label: 'LLM Final Response',
      type: 'llm' as const,
      detail: 'Groq synthesized tool results into natural-language intelligence report.\nTokens used: ~1,200\nLatency: 890ms',
    },
  ];

  return (
    <div className="max-h-[500px] overflow-y-auto pr-2 space-y-0">
      {steps.map((s, i) => (
        <div key={s.step} className="flex gap-4">
          {/* Timeline */}
          <div className="flex flex-col items-center">
            <div className={`w-7 h-7 rounded-full border flex items-center justify-center text-[10px] font-bold font-mono shrink-0 ${
              s.type === 'input' ? 'border-accent-amber/40 text-accent-amber bg-accent-amber/5' :
              s.type === 'llm' ? 'border-accent-blue/40 text-accent-blue bg-accent-blue/5' :
              s.type === 'tool' ? 'border-purple-500/40 text-purple-400 bg-purple-500/5' :
              'border-accent-green/40 text-accent-green bg-accent-green/5'
            }`}>
              {s.step}
            </div>
            {i < steps.length - 1 && <div className="w-px flex-1 bg-border my-1"></div>}
          </div>

          {/* Content */}
          <div className="pb-5 flex-1 min-w-0">
            <div className="flex items-center gap-2 mb-2">
              <span className="text-[12px] font-semibold text-primary">{s.label}</span>
              <span className={`text-[9px] font-mono px-1.5 py-0.5 rounded-full tracking-wider uppercase ${
                s.type === 'input' ? 'bg-accent-amber/10 text-accent-amber' :
                s.type === 'llm' ? 'bg-accent-blue/10 text-accent-blue' :
                s.type === 'tool' ? 'bg-purple-500/10 text-purple-400' :
                'bg-accent-green/10 text-accent-green'
              }`}>
                {s.type === 'input' ? 'INPUT' : s.type === 'llm' ? 'LLM' : s.type === 'tool' ? 'MCP' : 'DATABASE'}
              </span>
            </div>
            <pre className="text-[11px] font-mono text-muted leading-relaxed whitespace-pre-wrap bg-background border border-border rounded-md p-3">
              {s.detail}
            </pre>
          </div>
        </div>
      ))}
    </div>
  );
}

/* ── Meta Tab ── */
function MetaTab({ prompt }: { prompt: string }) {
  const meta = [
    { label: 'Session ID', value: `sess_${Math.random().toString(36).substring(2,10)}` },
    { label: 'Timestamp', value: new Date().toISOString() },
    { label: 'LLM Model', value: 'llama-3.3-70b-versatile' },
    { label: 'LLM Provider', value: 'Groq Cloud' },
    { label: 'MCP Server', value: '@clickhouse/mcp-server (stdio)' },
    { label: 'Database', value: 'ClickHouse Cloud (ap-northeast-1)' },
    { label: 'Max Tool Calls', value: '5' },
    { label: 'Tool Calls Used', value: '1' },
    { label: 'Backend Gateway', value: 'ASP.NET Core 10 (port 5000)' },
    { label: 'Agent Service', value: 'Node.js Express (port 3001)' },
  ];

  return (
    <div className="max-h-[500px] overflow-y-auto pr-2">
      <div className="grid grid-cols-2 gap-x-8 gap-y-4">
        {meta.map(m => (
          <div key={m.label}>
            <div className="text-[10px] font-semibold text-muted tracking-[0.12em] uppercase mb-1">{m.label}</div>
            <div className="text-[12px] font-mono text-secondary">{m.value}</div>
          </div>
        ))}
      </div>
    </div>
  );
}
