import { GitCompare, LineChart, FileLineChart } from 'lucide-react';

export default function PlaceholderView({ title, description, icon: Icon, action }: any) {
  return (
    <div className="p-8 max-w-5xl mx-auto animate-in fade-in duration-500 flex flex-col items-center justify-center h-[70vh] text-center">
      <div className="w-16 h-16 bg-surface-raised rounded-2xl flex items-center justify-center mb-6 border border-border">
        <Icon className="w-8 h-8 text-accent-blue" />
      </div>
      <h1 className="text-2xl font-bold text-primary tracking-tight mb-2">{title}</h1>
      <p className="text-secondary max-w-md">
        {description}
      </p>
      <button className="mt-8 px-6 py-2.5 bg-primary text-background rounded-md font-medium hover:bg-white/90">
        {action}
      </button>
    </div>
  );
}

export function ScenariosView() {
  return <PlaceholderView 
    icon={GitCompare} 
    title="Scenario Comparison Matrix" 
    description="Run parallel A/B tests on budget allocations for different VFX intensities and marketing strategies."
    action="Create New Scenario"
  />;
}

export function AnalyticsView() {
  return <PlaceholderView 
    icon={LineChart} 
    title="Deep Analytics Studio" 
    description="Build custom Recharts dashboards slicing historical ROI across international territories and demographics."
    action="Build Dashboard"
  />;
}

export function ReportsView() {
  return <PlaceholderView 
    icon={FileLineChart} 
    title="Saved AI Reports" 
    description="Browse previous Intelligence Reports generated by the Director Agent and export them directly to PDF or Excel."
    action="Browse Reports"
  />;
}
